# Generated by Django 4.1.2 on 2022-10-25 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Appraisal Date')),
                ('type', models.CharField(choices=[('L1', 'Personal Research'), ('L2', 'Informal Dealer Appraisal'), ('L3', 'Numismatic Guaranty Corporation Appraisal')], default='L1', max_length=2)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.coin')),
            ],
        ),
    ]
