# Generated by Django 4.1.2 on 2022-10-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_appraisal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appraisal',
            new_name='Appraising',
        ),
    ]
