# Generated by Django 4.1.2 on 2022-10-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_appraisal_appraising'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=30)),
                ('date', models.DateField(verbose_name='Show Date')),
            ],
        ),
        migrations.AlterModelOptions(
            name='appraising',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='coin',
            name='shows',
            field=models.ManyToManyField(to='main_app.show'),
        ),
    ]
